from rl_x.environments.environment_manager import extract_environment_name_from_file, register_environment
from one_policy_to_run_them_all.environments.unitree_go2.create_env import create_env
from one_policy_to_run_them_all.environments.unitree_go2.default_config import get_config
from one_policy_to_run_them_all.environments.unitree_go2.general_properties import GeneralProperties


UNITREE_A1 = extract_environment_name_from_file(__file__)
register_environment(UNITREE_A1, get_config, create_env, GeneralProperties)
