from rl_x.environments.environment_manager import extract_environment_name_from_file, register_environment
from one_policy_to_run_them_all.environments.honey_badger.create_env import create_env
from one_policy_to_run_them_all.environments.honey_badger.default_config import get_config
from one_policy_to_run_them_all.environments.honey_badger.general_properties import GeneralProperties


HONEY_BADGER = extract_environment_name_from_file(__file__)
register_environment(HONEY_BADGER, get_config, create_env, GeneralProperties)
