from rl_x.environments.environment_manager import extract_environment_name_from_file, register_environment
from one_policy_to_run_them_all.environments.multi_robot.create_env import create_env
from one_policy_to_run_them_all.environments.multi_robot.default_config import get_config
from one_policy_to_run_them_all.environments.multi_robot.general_properties import GeneralProperties


MULTI_ROBOT = extract_environment_name_from_file(__file__)
register_environment(MULTI_ROBOT, get_config, create_env, GeneralProperties)
